include:
  - local: .gitlab/ci/base.yml
  - local: .gitlab/ci/quality.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/security.yml
  - local: .gitlab/ci/release.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
