stages:
  - quality
  - test
  - security
  - release
  - docker

.uv-base:
  image: ghcr.io/astral-sh/uv:python3.13-trixie
  before_script:
    - uv sync --group dev --frozen
  cache:
    key: uv-${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/
