pip-audit:
  extends: .uv-base
  stage: security
  script:
    - make audit

gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks:v8.30.1
    entrypoint: [""]
  rules:
    - if: '$RENOVATE == "true"'
      when: never
    - when: on_success
  script:
    - gitleaks detect --source . --verbose --redact

trivy:
  stage: security
  image:
    name: ghcr.io/aquasecurity/trivy:0.70.0
    entrypoint: [""]
  rules:
    - if: '$RENOVATE == "true"'
      when: never
    - when: on_success
  script:
    - trivy fs .
